/**
 * Generated by tsnapi — public API snapshot of `klipy-sdk`
 */
// #region Interfaces
export interface GifSearchParams {
  q: string;
  customerId?: string;
  page?: number;
  perPage?: number;
  locale?: string;
  contentFilter?: 'off' | 'low' | 'medium' | 'high';
}
export interface KlipyClientOptions {
  apiKey: string;
}
// #endregion

// #region Classes
export declare class KlipyClient {
  private readonly apiKey;
  private readonly baseUrl;
  constructor(_: KlipyClientOptions);
  private request;
  gifs: {
    search: (_: GifSearchParams) => Promise<KlipyPage<KlipyItem>>;
  };
}
// #endregion