/**
 * Generated by tsnapi — public API snapshot of `klipy-sdk`
 */
// #region Interfaces
export interface KlipyClientOptions {
  apiKey: string;
}
// #endregion

// #region Classes
export declare class KlipyClient {
  private readonly apiKey;
  private readonly baseUrl;
  constructor(_: KlipyClientOptions);
  private request;
  gifs: {
    search: (_: GifSearchParams) => Promise<KlipyPage>;
    trending: (_: GifTrendingParams) => Promise<KlipyPage>;
    categories: (_: GifCategoriesParams) => Promise<KlipyCategoryPage>;
    recent: (_: GifRecentParams) => Promise<KlipyPage>;
    items: (_: GifItemsParams) => Promise<KlipyItemsPage>;
  };
}
// #endregion