/**
 * Generated by tsnapi — public API snapshot of `klipy-js`
 */
// #region Interfaces
export interface CategoriesData {
  locale: string;
  categories: Category[];
}
export interface Category {
  category: string;
  query: string;
  preview_url: string;
}
export interface ClipItem {
  url: string;
  title: string;
  slug: string;
  file: ClipFile;
  file_meta: ClipFormats;
  tags: string[];
  type: 'clip';
  blur_preview: string;
}
export interface ClipPage {
  data: ClipItem[];
  meta: Meta;
}
export interface ClipPaginatedPage extends ClipPage, Pagination {}
export interface MediaCategoriesParams {
  locale?: string;
}
export interface MediaHideFromRecentsParams {
  slug: string;
  customerId: string;
}
export interface MediaItem<T extends MediaContentType> {
  id: number;
  slug: string;
  title: string;
  file: MediaFile<FormatVariantMap[T]>;
  tags: string[];
  type: T;
  blur_preview: string;
}
export interface MediaItemsParams {
  slugs: string;
}
export interface MediaPage<T extends MediaContentType> {
  data: MediaItem<T>[];
  meta: Meta;
}
export interface MediaPaginatedPage<T extends MediaContentType> extends MediaPage<T>, Pagination {}
export interface MediaPaginationParams {
  page?: number;
  perPage?: number;
}
export interface MediaRecentParams extends MediaPaginationParams {
  customerId: string;
}
export interface MediaReportParams {
  slug: string;
  reason: MediaReportReasons;
  customerId?: string;
}
export interface MediaSearchParams extends MediaTrendingParams {
  q: string;
}
export interface MediaShareTriggerParams {
  slug: string;
  q?: string;
  customerId?: string;
}
export interface MediaTrendingParams extends MediaPaginationParams {
  customerId?: string;
  locale?: string;
  formatFilter?: FormatFilter;
  contentFilter?: ContentFilter;
}
export interface Meta {
  item_min_width: number;
  ad_max_resize_percent: number;
}
export interface Pagination {
  current_page: number;
  per_page: number;
  has_next: boolean;
}
export interface Rendition {
  url: string;
  width: number;
  height: number;
  size: number;
}
// #endregion

// #region Types
export type ClipClient = ClipClient$1;
export type ContentFilter = 'off' | 'low' | 'medium' | 'high';
export type EmojiClient = MediaClientFor<'emoji'>;
export type FormatFilter = 'gif' | 'webp' | 'jpg' | 'mp4' | 'webm';
export type GifClient = MediaClientFor<'gif'>;
export type MediaContentType = 'gif' | 'sticker' | 'meme' | 'emoji';
export type MediaReportReasons = 'nudity' | 'violence' | 'hate_speech' | 'harassment' | 'spam' | 'misinformation' | 'copyright' | 'offensive' | 'illegal' | 'broken' | 'low_quality' | 'not_relevant';
export type MemeClient = MediaClientFor<'meme'>;
export type StickerClient = MediaClientFor<'sticker'>;
// #endregion

// #region Classes
export declare class KlipyApiError extends Error {
  readonly status: number;
  readonly statusText: string;
  readonly body: unknown;
  constructor(_: number, _: string, _: unknown);
}
export declare class KlipyClient {
  readonly gifs: GifClient;
  readonly stickers: StickerClient;
  readonly memes: MemeClient;
  readonly emojis: EmojiClient;
  readonly clips: ClipClient$1;
  constructor({
    apiKey
  }: KlipyClientOptions);
}
// #endregion