/**
 * Generated by tsnapi — public API snapshot of `klipy-js`
 */
// #region Interfaces
export interface CategoriesData {
  locale: string;
  categories: Category[];
}
export interface Category {
  category: string;
  query: string;
  preview_url: string;
}
export interface HttpClientOptions {
  apiKey: string;
}
export interface KlipyClientOptions {
  apiKey: string;
}
export interface KlipyResponse<T> {
  result: boolean;
  data: T;
}
export interface MediaCategoriesParams {
  locale?: string;
}
export interface MediaFile<TFormat> {
  hd: TFormat;
  md: TFormat;
  sm: TFormat;
  xs: TFormat;
}
export interface MediaFormats {
  gif: Rendition;
  webp: Rendition;
  jpg: Rendition;
  png: Rendition;
  mp4: Rendition;
  webm: Rendition;
}
export interface MediaHideFromRecentsParams {
  slug: string;
  customerId: string;
}
export interface MediaItem<T extends MediaContentType> {
  id: number;
  slug: string;
  title: string;
  file: MediaFile<FormatVariantMap[T]>;
  tags: string[];
  type: T;
  blur_preview: string;
}
export interface MediaItemsParams {
  slugs: string;
}
export interface MediaPage<T extends MediaContentType> {
  data: MediaItem<T>[];
  meta: Meta;
}
export interface MediaPaginatedPage<T extends MediaContentType> extends MediaPage<T>, Pagination {}
export interface MediaPaginationParams {
  page?: number;
  perPage?: number;
}
export interface MediaRecentParams extends MediaPaginationParams {
  customerId: string;
}
export interface MediaReportParams {
  slug: string;
  reason: MediaReportReasons;
  customerId?: string;
}
export interface MediaSearchParams extends MediaTrendingParams {
  q: string;
}
export interface MediaShareTriggerParams {
  slug: string;
  q?: string;
  customerId?: string;
}
export interface MediaTrendingParams extends MediaPaginationParams {
  customerId?: string;
  locale?: string;
  formatFilter?: FormatFilter;
  contentFilter?: ContentFilter;
}
export interface Meta {
  item_min_width: number;
  ad_max_resize_percent: number;
}
export interface Pagination {
  current_page: number;
  per_page: number;
  has_next: boolean;
}
// #endregion

// #region Types
export type MediaContentType = 'gif' | 'sticker' | 'meme' | 'emoji';
// #endregion

// #region Classes
export declare class KlipyClient {
  readonly gifs: MediaClient<MediaPaginatedPage<'gif'>, MediaPage<'gif'>>;
  readonly stickers: MediaClient<MediaPaginatedPage<'sticker'>, MediaPage<'sticker'>>;
  readonly memes: MediaClient<MediaPaginatedPage<'meme'>, MediaPage<'meme'>>;
  readonly emojis: MediaClient<MediaPaginatedPage<'emoji'>, MediaPage<'emoji'>>;
  readonly clips: ClipClient;
  constructor({
    apiKey
  }: KlipyClientOptions);
}
// #endregion